### ISSUE TITLE
"AttributeError: module 'deep_tabular_augmentation' has no attribute 'AutoencoderModel'"

### ISSUE THREAD

**Issue by Nada-Bu** [lschmiddey/fastpages_#12]
Hi,

I have tried to execute the tutorial on this page:
https://github.com/lschmiddey/fastpages_/blob/master/_notebooks/2021-04-10-DeepLearning_TabularDataAugmentation.ipynb

But when I installed the library and initiated the model, I got this error:
AttributeError: module 'deep_tabular_augmentation' has no attribute 'AutoencoderModel'

Thanks

**Comment by lschmiddey** [comment]
Hi Nada,

I did some refactoring to the package since then, basically the model itself is now only called "Autoencoder":

`D_in = X_train_fraud.shape[1]
VAE_arch = [50, 12, 12]
target_name = 'Class'
target_class = 1
df_cols = list(df.columns)

model = dta.Autoencoder(D_in, VAE_arch, latent_dim=5).to(device)`

Try for example this tutorial here: https://lschmiddey.github.io/fastpages_/2022/02/19/DataAugmentation_vs_SMOTE.html

I hope this helps :) If not just message me.

Lasse

**Comment by Nada-Bu** [comment]
Hi Lasse,

Sorry, I followed an old tutorial -_-.
Thank you very much for the clarification.
